global:
  #  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: <api_slack>
        channel: '#skripsi'
        send_resolved: true     # Kirim notifikasi juga saat alert sudah resolved
        text: "<!channel> \nAlert Summary: {{ .CommonAnnotations.summary }}\nAlert Description: {{ .CommonAnnotations.description }}\nAll Data: {{ . }}"



          
          
          #templates:
          #  - /etc/alertmanager/templates/slack.tmpl