global:
  scrape_interval: 5s

remote_write:
  - url: "http://prometheus:9090/api/v1/write"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
       
 - job_name: 'node-exporter-swarm'
   metrics_path: /metrics
   static_configs:
     - targets: 
       - 'Node1:9100'
       - 'Node2:9100'
       - 'Node3:9100'
       - 'Node4:9100'
       - 'Node5:9100'

 - job_name: 'cadvisor-swarm'
   #metrics_path: /containers/
   static_configs:
     - targets:
       - 'Node1:8081'
       - 'Node2:8081'
       - 'Node3:8081'
       - 'Node4:8081'
       - 'Node5:8081'

#ganti port job kube ke nodeport
 - job_name: 'node-exporter-kube'
   metrics_path: /metrics
   static_configs:
     - targets: 
       - 'Node1:9100'
       - 'Node2:9100'
       - 'Node3:9100'
       - 'Node4:9100'
       - 'Node5:9100'

 - job_name: 'cadvisor-kube'
   #metrics_path: /containers/
   static_configs:
     - targets:
       - 'Node1:8081'
       - 'Node2:8081'
       - 'Node3:8081'
       - 'Node4:8081'
       - 'Node5:8081'