global:
  scrape_interval: 10s

scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090

 - job_name: 'node-exporter'
   metrics_path: /metrics
   static_configs:
     - targets: 
       - 'Node1:9100'
       - 'Node2:9100'
       - 'Node3:9100'
       - 'Node4:9100'
       - 'Node5:9100'

 - job_name: 'cadvisor'
   #metrics_path: /containers/
   static_configs:
     - targets:
       - 'Node1:8081'
       - 'Node2:8081'
       - 'Node3:8081'
       - 'Node4:8081'
       - 'Node5:8081'