version: '3.8'

services:
  nginx:
    restart: always
    image: nginx:stable-alpine3.20-perl
    container_name: nginxx
    networks:
      - liownet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt/certbot/www/:/var/www/certbot/:ro
      - ./letsencrypt/certbot/conf/ssl/:/etc/ssl-nya-bang/:ro
      - ./letsencrypt/certbot/conf/:/etc/letsencrypt/:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - liownet
    ports:
      - "3000"
    environment:
      - GF_AUTH_BASIC_ENABLED= true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost:80
      - GF_SERVER_ROOT_URL=https://${IP_A}:80/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"
    networks:
      - liownet
    ports:
      - "9090" 

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    restart: always
    ports:
      - '9115'
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    networks:
      - liownet
  

volumes:
  grafana-data:
  prometheus-data:

networks:
  liownet:
    driver: bridge